// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions, Firebase;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
void main() async {

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

}
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMivZbBmqt0ok6zhWSkcvmxWRZakLrWz0',
    appId: '1:536099252904:web:7f418fa7d22bba77bd309d',
    messagingSenderId: '536099252904',
    projectId: 'sanaetmemusi-f7434',
    authDomain: 'sanaetmemusi-f7434.firebaseapp.com',
    storageBucket: 'sanaetmemusi-f7434.firebasestorage.app',
    measurementId: 'G-LM0FW3T41S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTvM6CJAKozd3eLz4InmSVPE07j0rCh7M',
    appId: '1:536099252904:android:5d6b94ec8d640baabd309d',
    messagingSenderId: '536099252904',
    projectId: 'sanaetmemusi-f7434',
    storageBucket: 'sanaetmemusi-f7434.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjJO2D5oRLAQ5lzJ9Y8KZTXlev4bPWrlI',
    appId: '1:536099252904:ios:2a4659a21da3359bbd309d',
    messagingSenderId: '536099252904',
    projectId: 'sanaetmemusi-f7434',
    storageBucket: 'sanaetmemusi-f7434.firebasestorage.app',
    iosBundleId: 'com.example.personalWebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjJO2D5oRLAQ5lzJ9Y8KZTXlev4bPWrlI',
    appId: '1:536099252904:ios:2a4659a21da3359bbd309d',
    messagingSenderId: '536099252904',
    projectId: 'sanaetmemusi-f7434',
    storageBucket: 'sanaetmemusi-f7434.firebasestorage.app',
    iosBundleId: 'com.example.personalWebsite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMivZbBmqt0ok6zhWSkcvmxWRZakLrWz0',
    appId: '1:536099252904:web:59ca1a04e0148311bd309d',
    messagingSenderId: '536099252904',
    projectId: 'sanaetmemusi-f7434',
    authDomain: 'sanaetmemusi-f7434.firebaseapp.com',
    storageBucket: 'sanaetmemusi-f7434.firebasestorage.app',
    measurementId: 'G-FMJKXZWKX5',
  );
}
